// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhGmb61wtchJaWmzlcsCaaqFqkmJ9kEhY',
    appId: '1:720253321912:web:ce0b09203f097db5022a4d',
    messagingSenderId: '720253321912',
    projectId: 'authtut-609f4',
    authDomain: 'authtut-609f4.firebaseapp.com',
    storageBucket: 'authtut-609f4.firebasestorage.app',
    measurementId: 'G-CPFQQ1371P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2EUd_q4cjMH6o144pii9KUH9VsTG_VsI',
    appId: '1:720253321912:android:3d7eb2b43108b4b6022a4d',
    messagingSenderId: '720253321912',
    projectId: 'authtut-609f4',
    storageBucket: 'authtut-609f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa_DVZDRyYD9B8ZJenD0OPLRzyrG059n8',
    appId: '1:720253321912:ios:2fa65b2e46483c77022a4d',
    messagingSenderId: '720253321912',
    projectId: 'authtut-609f4',
    storageBucket: 'authtut-609f4.firebasestorage.app',
    androidClientId: '720253321912-m42si6fde1eoq1jovjsf0vm740ldf2ie.apps.googleusercontent.com',
    iosClientId: '720253321912-rtngahhf3m24lnfmqhdvlqu4cmn4pjkb.apps.googleusercontent.com',
    iosBundleId: 'com.example.xnl',
  );

}